rudderlabs/rudder-sdk-ios

Example/Rudder/_AppDelegate.m, README.md, Rudder.podspec, Rudder/Classes/EventRepository.m
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/14)
=> Life cycle event fix

Rudder/Classes/DBPersistentManager.h, Rudder/Classes/DBPersistentManager.m, Rudder/Classes/EventRepository.h, Rudder/Classes/EventRepository.m, Rudder/Classes/RudderDBMessage.h, Rudder/Classes/Utils.h, Rudder/Classes/Utils.m
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/17)
=> Event and batch size

Example/Rudder/_AppDelegate.m, Example/Rudder/_ViewController.m, Rudder/Classes/DBPersistentManager.h, Rudder/Classes/DBPersistentManager.m, Rudder/Classes/EventRepository.h, Rudder/Classes/EventRepository.m, Rudder/Classes/UIViewController+RudderScreen.m
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/18)
=> Added support for turning off the source from dashboard

Example/Rudder.xcodeproj/project.pbxproj, Example/Rudder/Rudder-Info.plist, Example/Rudder/_AppDelegate.m, Rudder.podspec, Rudder/Classes/EventRepository.m, Rudder/Classes/RudderLibraryInfo.m, Rudder/Classes/Utils.m
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/19)
=> Fix for urlOptionsLaunch crash

.gitignore, Example/Rudder.xcodeproj/project.pbxproj, Example/Rudder/_AppDelegate.m, Example/Rudder/_ViewController.m, Rudder/Classes/RSContext.h, Rudder/Classes/RSContext.m, Rudder/Classes/RSDeviceInfo.h, Rudder/Classes/RSDeviceInfo.m, Rudder/Classes/RSElementCache.m
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/32)
=> advertisement id

Rudder/Classes/RSApp.m
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/36)
=> Fixes for app.version and app.build

Rudder/Classes/RSDBPersistentManager.m
Resolves #34
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/35)
=> [BugFix] Handling for single quotes in properties

Rudder/Classes/RSConfigBuilder.m
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/33)
=> addressed issue related to dataplaneurl in ios

.gitignore, Example/Rudder.xcodeproj/project.pbxproj, Example/Rudder/_AppDelegate.m, Example/Rudder/_ViewController.m, README.md, Rudder.podspec, Rudder/Classes/RSConfigBuilder.m, Rudder/Classes/RSConstants.m, Rudder/Classes/RSContext.h, Rudder/Classes/RSContext.m, Rudder/Classes/RSDeviceInfo.h, Rudder/Classes/RSDeviceInfo.m, Rudder/Classes/RSElementCache.m, Rudder/Classes/RSEventRepository.m, Rudder/Classes/RSServerConfigManager.h, Rudder/Classes/RSServerConfigManager.m
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/38)
=> V1.0.4 exponentialbackoff

README.md, Rudder.podspec, Rudder/Classes/RSConstants.m, Rudder/Classes/RSDeviceInfo.m
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/42)
=> Handled case sensitive device.type

Example/Rudder/_AppDelegate.m, Example/Rudder/_ViewController.m, README.md, Rudder.podspec, Rudder/Classes/RSClient.m, Rudder/Classes/RSConstants.m, Rudder/Classes/RSContext.h, Rudder/Classes/RSContext.m, Rudder/Classes/RSElementCache.h, Rudder/Classes/RSElementCache.m, Rudder/Classes/RSMessage.h, Rudder/Classes/RSMessage.m, Rudder/Classes/RSMessageBuilder.m, Rudder/Classes/RSOption.h, Rudder/Classes/RSOption.m, Rudder/Classes/RSPreferenceManager.h, Rudder/Classes/RSPreferenceManager.m, Rudder/Classes/RSUtils.h, Rudder/Classes/RSUtils.m
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/43)
=> externalId

README.md, Rudder.podspec, Rudder/Classes/RSClient.m, Rudder/Classes/RSConstants.m, Rudder/Classes/RSContext.h, Rudder/Classes/RSContext.m, Rudder/Classes/RSElementCache.h, Rudder/Classes/RSElementCache.m, Rudder/Classes/RSEventRepository.m, Rudder/Classes/RSMessageBuilder.m, Rudder/Classes/RSTraits.m
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/44)
=> Fixes for device-mode event replay queue

Example/Rudder/_AppDelegate.m, Example/Rudder/_ViewController.m, README.md, Rudder.podspec, Rudder/Classes/RSClient.m, Rudder/Classes/RSConstants.m
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/47)
=> Fixed crash for alias call

Rudder/Classes/RSClient.h, Rudder/Classes/RSClient.m, Rudder/Classes/RSEventRepository.h
ReactNative: add support for tracking lifecycle events
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/48)
=> RN: add support for tracking lifecycle events

Rudder/Classes/RSEventRepository.m, Rudder/Classes/RSServerConfigManager.h, Rudder/Classes/RSServerConfigManager.m
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/49)
=> Fetch config from backend on each app open

Example/Rudder/_AppDelegate.m, README.md, Rudder.podspec, Rudder/Classes/RSClient.h, Rudder/Classes/RSClient.m, Rudder/Classes/RSConstants.m, Rudder/Classes/RSContext.m, Rudder/Classes/RSElementCache.m, Rudder/Classes/RSMessage.m, Rudder/Classes/RSPreferenceManager.h, Rudder/Classes/RSPreferenceManager.m, Rudder/Classes/RSTraits.m
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/51)
=> Added support for setting anoymousId externally

README.md, Rudder.podspec, Rudder/Classes/RSConstants.m, Rudder/Classes/RSContext.m
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/52)
=> removed bug for reset calls

Example/Rudder/_AppDelegate.m, README.md, Rudder.podspec, Rudder/RSConstants.m, Rudder/RSContext.m
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/59)
=> Fixes for userAgent being unknown

Rudder/RSServerConfigManager.m
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/60)
=> Fixed Control Plane Urls having '/' as path

README.md, Rudder.podspec, Rudder/RSConstants.m
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/61)
=> Bumped version to 1.0.15

Package.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/64)
=> Fixed Swift package manager paths

Example/Rudder/_AppDelegate.m, README.md, Rudder.podspec, Rudder/RSConstants.m, Rudder/RSContext.h, Rudder/RSContext.m, Rudder/RSDeviceInfo.h, Rudder/RSDeviceInfo.m
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/65)
=> ATTrackingStatus implementation

README.md, Rudder.podspec, Rudder/RSConstants.m, Rudder/RSContext.m
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/67)
=> Reset Traits on Successive Identify calls with Different UserId's

Rudder.podspec, Rudder/RSEventRepository.m
…ntRepository
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/70)
=> Synchronized EventReplayMessage queue and moved its initialization to constructor

Example/Podfile.lock, Example/Rudder.xcworkspace/contents.xcworkspacedata, Example/Rudder.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Rudder/Rudder.xcodeproj/project.pbxproj, Rudder/Rudder/Domain/Models/RSApp.swift, Rudder/Rudder/Domain/Models/RSContext.swift, Rudder/Rudder/Domain/Models/RSDeviceInfo.swift, Rudder/Rudder/Domain/Models/RSLibraryInfo.swift, Rudder/Rudder/Domain/Models/RSMessage.swift, Rudder/Rudder/Domain/Models/RSMessageType.swift, Rudder/Rudder/Domain/Models/RSNetwork.swift, Rudder/Rudder/Domain/Models/RSOSInfo.swift, Rudder/Rudder/Domain/Models/RSScreenInfo.swift, Rudder/Rudder/Domain/Models/RSTraits.swift, Rudder/Rudder/Domain/Models/RSUtils.swift, Rudder/Rudder/Managers/RSPreferenceManager.swift
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/73)
=> Developed Basic Models and Preference Manager

Example/Rudder/_AppDelegate.m, Rudder/RSElementCache.m
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/74)
=> Fixed Crashing issue on Identify calls

Rudder.podspec, Rudder/RSEventRepository.m
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/69)
=> Fixed 500 errors being reported as WriteKey Errors

Example/Rudder.xcodeproj/project.pbxproj, Example/Rudder/CustomIntegration.m, Rudder/RSClient.h, Rudder/RSClient.m, Rudder/RSEventRepository.h, Rudder/RSEventRepository.m, Rudder/RSIntegration.h
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/76)
=> Added Flush Support for Device Mode Integrations

Rudder/RSLogger.m
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/75)
=> Defaulting Loglevel to RSLogLevelInfo 

Rudder/RSClient.h, Rudder/RSClient.m, Rudder/RSEventRepository.h, Rudder/RSEventRepository.m, Rudder/RSPreferenceManager.h, Rudder/RSPreferenceManager.m
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/77)
=> Added Initial changes for GDPR Support in iOS SDK

README.md, Rudder.podspec, Rudder/RSConstants.m
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/78)
=> Bumped version to 1.0.23

README.md
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/80)
=> Changed SDK Version to 1.0.22 in Readme

Rudder.podspec, Rudder/RSClient.h, Rudder/RSClient.m, Rudder/RSConstants.m, Rudder/RSEventRepository.h, Rudder/RSEventRepository.m, Rudder/RSPreferenceManager.h, Rudder/RSPreferenceManager.m
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/81)
=> GDPR implementation iOS

README.md, Rudder.podspec, Sources/Classes/RSConstants.m
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/96)
=> Bumped version to 1.1.3

.gitignore, CHANGELOG.md, README.md, Rudder.podspec, Rudder.xcodeproj/project.pbxproj, Sources/Classes/RSConstants.m
> Version bump to 1.1.4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/98)
=> Version bump

CHANGELOG.md, README.md, Rudder.podspec, Rudder.xcodeproj/project.pbxproj, Sources/Classes/RSConstants.m, Sources/Classes/RSUtils.m
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/100)
=> [Bugfix] Timestamp issue.

CHANGELOG.md, Examples/RudderSampleAppObjC/RudderSampleAppObjC/_AppDelegate.m, README.md, Rudder.podspec, Rudder.xcodeproj/project.pbxproj, Sources/Classes/Public/RSClient.h, Sources/Classes/RSClient.m, Sources/Classes/RSConstants.m
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/102)
=> [Bugix] Method 'setAnonymousId' marked as deprecated method

Sources/Classes/Public/RSContext.h, Sources/Classes/Public/RSElementCache.h, Sources/Classes/Public/RSEventRepository.h, Sources/Classes/RSClient.m, Sources/Classes/RSContext.m, Sources/Classes/RSElementCache.m, Sources/Classes/RSEventRepository.m
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/105)
=> Fixed InConsistencies in AnonymousID Updations

CHANGELOG.md, Podfile.lock, README.md, Rudder.podspec, Rudder.xcodeproj/project.pbxproj, Sources/Classes/Public/RSContext.h, Sources/Classes/Public/RSElementCache.h, Sources/Classes/Public/RSEventRepository.h, Sources/Classes/RSClient.m, Sources/Classes/RSConstants.m, Sources/Classes/RSContext.m, Sources/Classes/RSElementCache.m, Sources/Classes/RSEventRepository.m
- Removed properties from Application Opened event which are not set
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/104)
=> Removed properties from Application Opened which are not set

CHANGELOG.md, Podfile.lock, README.md, Rudder.podspec, Sources/Classes/Public/RSConfigBuilder.h, Sources/Classes/Public/RSEventRepository.h, Sources/Classes/RSConstants.m, Sources/Classes/RSEventRepository.m
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/109)
=> Added support for extending background run time in watchOS

CODEOWNERS
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/110)
=> Merge back master to develop

CHANGELOG.md, README.md, Rudder.podspec, Rudder.xcodeproj/project.pbxproj, Rudder.xcworkspace/contents.xcworkspacedata, Sources/Classes/RSConstants.m
> Added supported platform from build settings.
- https://www.notion.so/rudderstacks/Carthage-build-issue-861289403b91486fbd1c487a98ceb4bf
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/111)
=> [Bugfix] Fixed building issue via Carthage for watchOS, tvOS

CHANGELOG.md, Podfile.lock, README.md, Rudder.podspec, Rudder.xcodeproj/project.pbxproj, Rudder.xcworkspace/contents.xcworkspacedata, Sources/Classes/Public/RSConfigBuilder.h, Sources/Classes/Public/RSEventRepository.h, Sources/Classes/RSConstants.m, Sources/Classes/RSEventRepository.m
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/112)
=> Develop -> Master

CHANGELOG.md, README.md, Rudder.podspec, Sources/Classes/RSConstants.m, Sources/Classes/RSEventRepository.m
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/113)
=> Using WeakSelf to fix the Memory Leak Issue

CHANGELOG.md, README.md, Rudder.podspec, Rudder.xcodeproj/project.pbxproj, Sources/Classes/Public/RSConstants.h, Sources/Classes/Public/RSEventFilteringPlugin.h, Sources/Classes/Public/RSEventRepository.h, Sources/Classes/RSConstants.m, Sources/Classes/RSEventFilteringPlugin.m, Sources/Classes/RSEventRepository.m
[Feature] Added Support for Client Side Event Filtering for Device Mode Destinations
Notion Link: [here](https://www.notion.so/rudderstacks/Event-Filtering-iOS-c1a4b5399cdf493faf6c1674a1f3e0d0)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/115)
=> [Feature] Added Support for Client Side Event Filtering for Device Mode Destinations

CHANGELOG.md, README.md, Rudder.podspec, Rudder.xcodeproj/project.pbxproj, Sources/Classes/Public/RSConstants.h, Sources/Classes/Public/RSEventFilteringPlugin.h, Sources/Classes/Public/RSEventRepository.h, Sources/Classes/RSConstants.m, Sources/Classes/RSEventFilteringPlugin.m, Sources/Classes/RSEventRepository.m
[Feature] Added Support for Client-Side Event Filtering for Device Mode Destinations
Notion Link: [here](https://www.notion.so/rudderstacks/Event-Filtering-iOS-c1a4b5399cdf493faf6c1674a1f3e0d0)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/116)
=> [Release] Version 1.5.0

.github/pull_request_template.md, .github/workflows/main.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/133)
=> [Enhancement] PR template added

.github/pull_request_template.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/137)
=> Update pull_request_template.md (#136)

README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/139)
=> [Enhancement] README updated

CHANGELOG.md, Podfile.lock, README.md, Rudder.podspec, Rudder.xcodeproj/project.pbxproj, Sources/Classes/Common/Constants/RSConstants.swift, Sources/Classes/Common/Constants/RSEventsAndKeys.swift
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/141)
=> [Enhancement] Added keys in RSEventsAndKeys

CHANGELOG.md, Podfile.lock, README.md, Rudder.podspec, Rudder.xcodeproj/project.pbxproj, Sources/Classes/Common/Constants/RSConstants.swift, Sources/Classes/Common/Constants/RSEventsAndKeys.swift
Added three keys: `promotionId`, `creative`, `interest` and `itemName` in RSEventsAndKeys.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/142)
=> [Release] Version 2.0.1

CHANGELOG.md, README.md, Rudder.podspec, Rudder.xcodeproj/project.pbxproj, Sources/Classes/Common/Constants/RSConstants.swift, Sources/Classes/Common/Constants/RSEventsAndKeys.swift
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/148)
=> Keys added

CHANGELOG.md, README.md, Rudder.podspec, Rudder.xcodeproj/project.pbxproj, Sources/Classes/Common/Constants/RSConstants.swift, Sources/Classes/Common/Constants/RSEventsAndKeys.swift
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/149)
=> [Enhancement] RSKeys added

CHANGELOG.md, Examples/SampleSwift-iOS-APNs/SampleSwift-iOS-APNs.xcodeproj/project.pbxproj, Examples/SampleSwift-iOS-APNs/SampleSwift-iOS-APNs.xcodeproj/project.xcworkspace/contents.xcworkspacedata, Examples/SampleSwift-iOS-APNs/SampleSwift-iOS-APNs.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Examples/SampleSwift-iOS-APNs/SampleSwift-iOS-APNs.xcodeproj/xcshareddata/xcschemes/SampleSwift-iOS-APNs.xcscheme, Examples/SampleSwift-iOS-APNs/SampleSwift-iOS-APNs/AppDelegate.swift, Examples/SampleSwift-iOS-APNs/SampleSwift-iOS-APNs/Assets.xcassets/AccentColor.colorset/Contents.json, Examples/SampleSwift-iOS-APNs/SampleSwift-iOS-APNs/Assets.xcassets/AppIcon.appiconset/Contents.json, Examples/SampleSwift-iOS-APNs/SampleSwift-iOS-APNs/Assets.xcassets/Contents.json, Examples/SampleSwift-iOS-APNs/SampleSwift-iOS-APNs/Base.lproj/LaunchScreen.storyboard, Examples/SampleSwift-iOS-APNs/SampleSwift-iOS-APNs/Base.lproj/Main.storyboard, Examples/SampleSwift-iOS-APNs/SampleSwift-iOS-APNs/Info.plist, Examples/SampleSwift-iOS-APNs/SampleSwift-iOS-APNs/RSCustomDestination.swift, Examples/SampleSwift-iOS-APNs/SampleSwift-iOS-APNs/SampleSwift-iOS-APNs.entitlements, Examples/SampleSwift-iOS-APNs/SampleSwift-iOS-APNs/SceneDelegate.swift, Examples/SampleSwift-iOS-APNs/SampleSwift-iOS-APNs/ViewController.swift, Examples/SampleSwift-iOS-APNs/SampleSwift-iOS-APNs/first.apn, Podfile, Podfile.lock, README.md, Rudder.podspec, Rudder.xcodeproj/project.pbxproj, Rudder.xcworkspace/contents.xcworkspacedata, Sources/Classes/Common/Constants/RSConstants.swift, Sources/Classes/Domain/Protocols/RSPushNotifications.swift, Sources/Classes/Helpers/Platforms/iOS/RSiOSDelegation.swift, Sources/Classes/Helpers/Platforms/watchOS/RSwatchOSDelegation.swift
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/151)
=> [Feature] Added support for APNs

README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/156)
=> [Feature] Added support for AppCenter device mode

README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/159)
=> [Feature] Added support for MoEngage device mode

Sources/Classes/Public/RSUtils.h, Sources/Classes/RSConfigBuilder.m, Sources/Classes/RSUtils.m
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/165)
=> Accepting path as well for both dataplane and controlplane url's

README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/167)
=> [Feature] Added support for AppsFlyer

.travis.yml, CHANGELOG.md, Examples/SampleSwift-iOS-APNs/SampleSwift-iOS-APNs/AppDelegate.swift, Examples/SampleSwift-iOS-APNs/SampleSwift-iOS-APNs/RSCustomDestination.swift, Examples/SampleSwift-iOS-APNs/SampleSwift-iOS-APNs/SceneDelegate.swift, Examples/SampleSwift-iOS-APNs/SampleSwift-iOS-APNs/ViewController.swift, Examples/SampleSwift-macOS/SampleSwift-macOS/AppDelegate.swift, Examples/SampleSwift-macOS/SampleSwift-macOS/ViewController.swift, Podfile.lock, README.md, Rudder.podspec, Rudder.xcodeproj/project.pbxproj, Sources/Classes/Client/Plugins/RudderDestinationPlugin.swift, Sources/Classes/Client/RSDatabaseManager.swift, Sources/Classes/Common/Constants/RSConstants.swift, Sources/Classes/Common/Constants/RSEventsAndKeys.swift, Tests/RudderTests/RSClientTests.swift, Tests/RudderTests/RSDatabaseTests.swift, Tests/RudderTests/RSIdentifyTests.swift, Tests/RudderTests/RSScreenTests.swift
> Added new set of keys in RSKeysAndEvents class. More details about the keys could be found inside Changelog.md file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/174)
=> [Release] Version 2.1.1

README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/180)
=> [Feature] Added support for Facebook App Events

CHANGELOG.md, README.md, Rudder.podspec, Rudder.xcodeproj/project.pbxproj, Sources/Classes/Common/Constants/RSConstants.swift
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/189)
=> [Release] Version 2.2.3

CHANGELOG.md, README.md, Rudder.podspec, Rudder.xcodeproj/project.pbxproj, Sources/Classes/Client/RSClient+Plugins.swift, Sources/Classes/Client/RSClient.swift, Sources/Classes/Common/Constants/RSConstants.swift
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/190)
=> [Release] Version 2.2.3 

CHANGELOG.md, Podfile.lock, README.md, Rudder.podspec, Rudder.xcodeproj/project.pbxproj, Sources/Classes/Common/Constants/RSConstants.swift, Sources/Classes/Common/Constants/RSEventsAndKeys.swift, Sources/Classes/Domain/Protocols/RSPushNotifications.swift, Sources/Classes/Helpers/Platforms/iOS/RSiOSDelegation.swift
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/194)
=> Added new keys and push notification API

CHANGELOG.md, Podfile.lock, README.md, Rudder.podspec, Rudder.xcodeproj/project.pbxproj, Sources/Classes/Common/Constants/RSConstants.swift, Sources/Classes/Common/Constants/RSEventsAndKeys.swift, Sources/Classes/Domain/Protocols/RSPushNotifications.swift, Sources/Classes/Helpers/Platforms/iOS/RSiOSDelegation.swift
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/195)
=> [Release] Version 2.2.4

CHANGELOG.md, README.md, Sources/Classes/Public/RSVersion.h, Sources/Classes/RSPreferenceManager.m, package.json
1.7.0 (2022-11-04)<br> * fix: session is generating on reset api even when session is disabled ([7585f3a](https://github.com/rudderlabs/rudder-sdk-ios/commit/7585f3a))<br> * ci: added CI/CD pipeline ([6f5124e](https://github.com/rudderlabs/rudder-sdk-ios/commit/6f5124e))
=> chore(release): pulling hotfix-release/1.7.1 into master

CHANGELOG.md, README.md, Sources/Classes/Public/RSVersion.h, Sources/Classes/RSPreferenceManager.m, package.json
=> chore(release): pulling master into develop post release v1.7.1

.github/workflows/draft-new-release.yml, .github/workflows/test.yml, .gitignore, Rudder.xcodeproj/project.pbxproj, sonar-project.properties
Sonarqube(cloud) added to repo and test ci.
=> ci: sonarcloud scan added to test ci

.github/workflows/draft-new-release.yml, .github/workflows/test.yml, .gitignore, Rudder.xcodeproj/project.pbxproj, sonar-project.properties
=> ci: added Test & Coverage CI

.github/workflows/publish-new-release.yml
=> ci: fix publish-new-release.yml

.github/workflows/build-and-quality-checks-v2.yml, .github/workflows/check-pr-title.yml, .github/workflows/create-hotfix-branch-v2.yml, .github/workflows/draft-new-release-v2.yml, .github/workflows/publish-new-release-v2.yml, .github/workflows/test-v2.yml
=> ci: added CI/CD pipeline for v2

.github/workflows/slack-notify.yml
=> ci: added Slack Notification ci

.github/workflows/slack-notify.yml, CHANGELOG.md, Podfile.lock, README.md, Sources/Classes/Public/RSVersion.h, Sources/Classes/RSEventRepository.m, package.json, sonar-project.properties
Unreleased (2022-11-17)<br> * fix: initialise  object even when  is empty ([3a5c1c4](https://github.com/rudderlabs/rudder-sdk-ios/commit/3a5c1c4))<br> * ci: added CI/CD pipeline for v2 ([e3d3acb](https://github.com/rudderlabs/rudder-sdk-ios/commit/e3d3acb))<br> * ci: added Slack Notification ci ([4706472](https://github.com/rudderlabs/rudder-sdk-ios/commit/4706472))<br> * ci: added Slack Notification ci ([7fa84d7](https://github.com/rudderlabs/rudder-sdk-ios/commit/7fa84d7))<br> * ci: added Test & Coverage CI ([6bbe4b9](https://github.com/rudderlabs/rudder-sdk-ios/commit/6bbe4b9))<br> * ci: fix publish-new-release.yml ([b9b182a](https://github.com/rudderlabs/rudder-sdk-ios/commit/b9b182a))
=> chore(release): pulling release/1.7.2 into master

SECURITY.md
Added SECURITY.md to the repo for reporting any security issues/concerns
=> docs: added SECURITY.md

.github/workflows/build-and-quality-checks-v2.yml, .github/workflows/build-and-quality-checks.yml, .github/workflows/create-hotfix-branch-v2.yml, .github/workflows/create-hotfix-branch.yml, .github/workflows/deploy-cocoapods.yml
Bump peterjgrainger/action-create-branch from 2.3.0 to 2.4.0
=> ci: bump peterjgrainger/action-create-branch from 2.3.0 to 2.4.0

.github/workflows/deploy-cocoapods-v2.yml
In deploy-cocoapods-v2.yml file
=> ci: add XCode version select action

.github/workflows/deploy-cocoapods-v2.yml
=> ci: select xcode version for deploy action

.github/workflows/deploy-cocoapods-manual.yml
Added CI for deploying to Cocoapods manually
=> ci: added support for deploying to Cocoapods manually

.github/workflows/deploy-cocoapods-manual-v2.yml
Added CI for deploy to Cocoapods manually
=> ci: added support for deploy to Cocoapods manually

.github/workflows/deploy-cocoapods-manual-v2.yml, .github/workflows/deploy-cocoapods-manual.yml
Added CI for deploy to Cocoapods manually
=>  ci(v2): added support for deploy to Cocoapods manually

.github/workflows/deploy-cocoapods-manual-v2.yml
=>  ci: added support for deploy to Cocoapods manually for v2

.github/workflows/deploy-cocoapods-manual-v2.yml, .github/workflows/deploy-cocoapods-manual.yml
=> ci: fix manual deploy to Cocoapods

.github/workflows/deploy-cocoapods-manual-v2.yml
=> ci: update deploy-cocoapods-manual-v2.yml

.github/workflows/build-and-quality-checks-v2.yml, .github/workflows/deploy-cocoapods-v2.yml, Podfile.lock, Sources/Classes/Client/Plugins/RSContextPlugin.swift
=> fix: improper way of handling customContext

Sources/Classes/Client/Plugins/RSAnonymousIdPlugin.swift, Sources/Classes/Networking/APIClient/RSServiceManager.swift
=> fix: enhance support for anonymousId for all supported platforms

.github/workflows/build-and-quality-checks-v2.yml, .github/workflows/deploy-cocoapods-v2.yml, CHANGELOG.md, Podfile.lock, README.md, Sources/Classes/Client/Plugins/RSAnonymousIdPlugin.swift, Sources/Classes/Client/Plugins/RSContextPlugin.swift, Sources/Classes/Common/Constants/RSVersion.swift, Sources/Classes/Networking/APIClient/RSServiceManager.swift, package.json, sonar-project.properties
<small>2.2.5 (2023-01-31)</small><br> * fix: enhance support for anonymousId for all supported platforms ( 257) ([60a0d70](https://github.com/rudderlabs/rudder-sdk-ios/commit/60a0d70)), closes [ 257](https://github.com/rudderlabs/rudder-sdk-ios/issues/257)<br> * fix: improper way of handling customContext ([9b2297e](https://github.com/rudderlabs/rudder-sdk-ios/commit/9b2297e))<br> * chore(release): 2.2.5 ([5288c40](https://github.com/rudderlabs/rudder-sdk-ios/commit/5288c40))
=> chore(release): pulling release/2.2.6 into master

CHANGELOG.md, README.md, Sources/Classes/Common/Constants/RSVersion.swift, package.json, sonar-project.properties
=> chore(release): pulling master into develop post release v2.2.6

Sources/Classes/RSDBPersistentManager.m
A crash was happening because of corrupt data. Handled corrupt data.
=> fix: handled corrupt data of database

.github/workflows/draft-new-release.yml, .github/workflows/publish-new-release.yml, Rudder.xcodeproj/project.pbxproj, github-release.config.js
=> fix: ci tag issue

.github/workflows/deploy-cocoapods-manual-v2.yml, .github/workflows/deploy-cocoapods-manual.yml, .github/workflows/draft-new-release-v2.yml, .github/workflows/publish-new-release-v2.yml, .github/workflows/publish-new-release.yml
Fix the following CIs:
- publish release(v1 and v2)
- draft release(v2)
- manually deploy(v1 and v2)
=> chore: fix ci

.github/workflows/draft-new-release.yml
Updated the path version header file in draft-new-release CI.
=> chore: update draft-new-release.yml

Podfile.lock, Sources/Classes/Client/Plugins/RSLoggerPlugin.swift, Sources/Classes/Client/RSClient+Plugins.swift
Config specified log level was not working.
=> fix: config specified log level is not working

.github/workflows/build-and-quality-checks-v2.yml, .github/workflows/build-and-quality-checks.yml, .github/workflows/deploy-cocoapods-beta.yml, .github/workflows/deploy-cocoapods-manual-v2.yml, .github/workflows/deploy-cocoapods-manual.yml, .github/workflows/deploy-cocoapods.yml, .github/workflows/draft-new-beta-release.yml
- Removed Xcode selected version as CocoaPods 1.12.0 fixed the previous issue. 
- Added ci for beta release
=> chore: remove Xcode selected version, added ci for beta release

.github/workflows/publish-new-release-v2.yml, .github/workflows/publish-new-release.yml, Podfile.lock
Delete the auto-created tag without 'v' before creating a github release.
=> chore: fix duplicate tag creation

Sources/Classes/RSConfigBuilder.m
Restricted nil assign of dataPlaneUrl and controlPlaneUrl
=> fix: restricted nil assign of dataPlaneUrl and controlPlaneUrl

Sources/Classes/RSNetwork.m, Sources/Classes/RSUtils.m, Tests/RudderUtilsTest.swift
=> fix: sending carrier as a comma separated string

CHANGELOG.md, README.md, Sources/Classes/Headers/Public/RSNetwork.h, Sources/Classes/Headers/RSVersion.h, Sources/Classes/RSNetwork.m, Sources/Classes/RSUtils.m, Tests/RudderUtilsTest.swift, package.json, sonar-project.properties
Unreleased (2023-05-09)<br> * feat: handled retrieving carrier names as per different iOS versions ([a81e3a2](https://github.com/rudderlabs/rudder-sdk-ios/commit/a81e3a2))
=> chore(release): pulling release/1.15.0 into master

CHANGELOG.md, README.md, Sources/Classes/Headers/Public/RSDBPersistentManager.h, Sources/Classes/Headers/RSVersion.h, Sources/Classes/RSDBPersistentManager.m, package.json, sonar-project.properties
Unreleased (2023-05-12)<br> * fix: fixed insert sql statements to support sqlite versions less than 3.35.0 ( 318) ([4ed5cc2](https://github.com/rudderlabs/rudder-sdk-ios/commit/4ed5cc2)), closes [ 318](https://github.com/rudderlabs/rudder-sdk-ios/issues/318)
=> chore(release): pulling release/1.15.1 into master

Sources/Classes/RSApplicationLifeCycleManager.m
Errors occurred during the SPM build.
=> chore: fix for SPM build

.github/workflows/draft-new-release-v2.yml, .github/workflows/draft-new-release.yml, .github/workflows/slack-notify.yml, CHANGELOG.md, Podfile.lock, README.md, Rudder.xcodeproj/project.pbxproj, Sources/Classes/Headers/Public/NSData+GZIP.h, Sources/Classes/Headers/Public/RSConfig.h, Sources/Classes/Headers/Public/RSConfigBuilder.h, Sources/Classes/Headers/Public/RSConstants.h, Sources/Classes/Headers/RSVersion.h, Sources/Classes/NSData+GZIP.m, Sources/Classes/RSApplicationLifeCycleManager.m, Sources/Classes/RSConfig.m, Sources/Classes/RSConfigBuilder.m, Sources/Classes/RSConstants.m, Sources/Classes/RSNetworkManager.m, package.json, sonar-project.properties
Unreleased (2023-06-08)<br> * chore: fix for SPM build ( 333) ([7867df3](https://github.com/rudderlabs/rudder-sdk-ios/commit/7867df3)), closes [ 333](https://github.com/rudderlabs/rudder-sdk-ios/issues/333)<br> * chore: lock conventional-changelog-cli to 2.2.2 in draft-new-release CIs ( 337) ([ddf7f08](https://github.com/rudderlabs/rudder-sdk-ios/commit/ddf7f08)), closes [ 337](https://github.com/rudderlabs/rudder-sdk-ios/issues/337)<br> * chore(deps): bump slackapi/slack-github-action from 1.23.0 to 1.24.0 ( 326) ([6cd98b3](https://github.com/rudderlabs/rudder-sdk-ios/commit/6cd98b3)), closes [ 326](https://github.com/rudderlabs/rudder-sdk-ios/issues/326)<br> * feat: added support for gzip ( 325) ([2e1fba0](https://github.com/rudderlabs/rudder-sdk-ios/commit/2e1f …
=> chore(release): pulling release/1.16.0 into master

.github/workflows/draft-new-release-v2.yml, .github/workflows/publish-new-release-v2.yml, Scripts/find-tag.sh, github-release.config.js
Sync the latest changes for v1 pipelines into v2 ones
=> ci: fix github releaser issue

Sources/Classes/Headers/Public/NSData+GZIP.h, Sources/Classes/NSData+GZIP.m
=> chore: added credit to NSData+GZIP

CHANGELOG.md, Podfile.lock, README.md, Sources/Classes/Headers/Public/NSData+GZIP.h, Sources/Classes/Headers/Public/RSApplicationLifeCycleManager.h, Sources/Classes/Headers/Public/RSDBMessage.h, Sources/Classes/Headers/Public/RSDBPersistentManager.h, Sources/Classes/Headers/Public/RSDeviceModeManager.h, Sources/Classes/Headers/Public/RSEnums.h, Sources/Classes/Headers/Public/RSUtils.h, Sources/Classes/Headers/RSVersion.h, Sources/Classes/NSData+GZIP.m, Sources/Classes/RSApplicationLifeCycleManager.m, Sources/Classes/RSDBPersistentManager.m, Sources/Classes/RSDeviceModeManager.m, Sources/Classes/RSEventRepository.m, Sources/Classes/RSPreferenceManager.m, Sources/Classes/RSUtils.m, Tests/DBPersistentManagerTests.swift, package.json, sonar-project.properties
=> chore(release): pulling master into develop post release v1.16.1

CHANGELOG.md, README.md, Sources/Classes/Client/Plugins/RSReplayQueuePlugin.swift, Sources/Classes/Client/RSClient+Plugins.swift, Sources/Classes/Common/Constants/RSVersion.swift, package.json, sonar-project.properties
Unreleased (2023-08-22)<br> * fix: device mode not initializing on first launch ([d82760c](https://github.com/rudderlabs/rudder-sdk-ios/commit/d82760c))
=> chore(release): pulling release/2.4.2 into master

CHANGELOG.md, README.md, Sources/Classes/Headers/Public/Rudder.h, Sources/Classes/Headers/RSVersion.h, package.json, sonar-project.properties
Unreleased (2023-08-23)<br> * fix: header not found issue on cross platforms ( 369) ([b9ba353](https://github.com/rudderlabs/rudder-sdk-ios/commit/b9ba353)), closes [ 369](https://github.com/rudderlabs/rudder-sdk-ios/issues/369)
=> chore(release): pulling release/1.19.1 into master

Package.resolved, Package.swift
Swift Package Manager build is failing.
=> fix: spm build error

.github/workflows/deploy-cocoapods.yml, .github/workflows/deploy-private-pod.yml, .github/workflows/slack-notify.yml, Sources/Classes/RSDBPersistentManager.m
Crash fix on RSDBPersistentManager.
=> fix: crash on RSDBPersistentManager

CHANGELOG.md, Examples/RudderSampleAppObjC/RudderSampleAppObjC/_AppDelegate.m, Podfile.lock, README.md, Sources/Classes/Headers/Public/RSPreferenceManager.h, Sources/Classes/Headers/Public/RSUserSession.h, Sources/Classes/Headers/RSVersion.h, Sources/Classes/RSEventRepository.m, Sources/Classes/RSPreferenceManager.m, Sources/Classes/RSUserSession.m, Tests/ContextTests.swift, package.json, sonar-project.properties
Unreleased (2023-11-14)<br> * fix: update lastActiveTimestamp value when reset call is made ( 412) ([6f229ad](https://github.com/rudderlabs/rudder-sdk-ios/commit/6f229ad)), closes [ 412](https://github.com/rudderlabs/rudder-sdk-ios/issues/412)
=> chore(release): pulling release/1.23.1 into master

Examples/RudderSampleAppObjC/RudderSampleAppObjC.xcodeproj/project.pbxproj, Examples/RudderSampleAppObjC/RudderSampleAppObjC.xcodeproj/xcshareddata/xcschemes/RudderSampleAppObjC.xcscheme, Examples/RudderSampleAppSwift/RudderSampleAppSwift.xcodeproj/project.pbxproj, Examples/RudderSampleApptvOSObjC/RudderSampleApptvOSObjC.xcodeproj/project.pbxproj, Examples/RudderSampleAppwatchOSObjC/RudderSampleAppwatchOSObjC.xcodeproj/project.pbxproj, Podfile, Podfile.lock, Rudder.podspec, Rudder.xcodeproj/project.pbxproj
=> chore: bumped version of MetricsReporter to 1.2.0

Package.swift, Podfile.lock, Rudder.podspec, Rudder.xcodeproj/project.pbxproj
updated version of MetricsReporter in package.swift
=> fix: updated version of MetricsReporter in package.swift

.github/workflows/publish-new-release.yml, CHANGELOG.md, Podfile.lock, README.md, Rudder.podspec, Sources/Classes/Headers/RSVersion.h, package.json, sonar-project.properties
Unreleased (2024-02-07)<br> * fix: correct file name of LICENSE.md file in Podspec ( 465) ([c46edc6](https://github.com/rudderlabs/rudder-sdk-ios/commit/c46edc6)), closes [ 465](https://github.com/rudderlabs/rudder-sdk-ios/issues/465)<br> * chore: updated changelog.md ([263aefd](https://github.com/rudderlabs/rudder-sdk-ios/commit/263aefd))<br> * chore(ci): fix publish new release github action ( 464) ([1d62dce](https://github.com/rudderlabs/rudder-sdk-ios/commit/1d62dce)), closes [ 464](https://github.com/rudderlabs/rudder-sdk-ios/issues/464)
=> chore(release): pulling release/1.25.1 into master

CHANGELOG.md, Examples/RudderSampleAppObjC/RudderSampleAppObjC.xcodeproj/project.pbxproj, README.md, Sources/Classes/Headers/RSVersion.h, Sources/Classes/RSUtils.m, Tests/ContextTests.swift, package.json, sonar-project.properties
Unreleased (2024-03-11)<br> * fix: create mutable copy of JSON serialisation object ( 479) ([95704e1](https://github.com/rudderlabs/rudder-sdk-ios/commit/95704e1)), closes [ 479](https://github.com/rudderlabs/rudder-sdk-ios/issues/479)
=> chore(release): pulling release/1.25.3 into master

.github/workflows/draft-new-release.yml, .github/workflows/publish-new-release.yml
- Change the PR Reviewer to SDK team
=> ci: change the PR reviewer to sdk team

.github/ISSUE_TEMPLATE/bug_report.md, .github/workflows/draft-new-release-v2.yml
- Change the PR reviewer to the SDK team
=> ci: change the PR reviewer to the sdk team

.github/ISSUE_TEMPLATE/bug_report.md, .github/workflows/draft-new-release-v2.yml, CHANGELOG.md, Package.swift, Podfile.lock, README.md, Rudder.podspec, Sources/Classes/Common/Constants/RSConstants.swift, Sources/Classes/Common/Constants/RSVersion.swift, Sources/Resources/PrivacyInfo.xcprivacy, package.json, sonar-project.properties
Unreleased (2024-04-08)<br> * ci: change the PR reviewer to sdk team ( 503) ([0c91eb2](https://github.com/rudderlabs/rudder-sdk-ios/commit/0c91eb2)), closes [ 503](https://github.com/rudderlabs/rudder-sdk-ios/issues/503)<br> * feat: add privacy manifest file support for ios v2 sdk ( 496) ([cb7ec68](https://github.com/rudderlabs/rudder-sdk-ios/commit/cb7ec68)), closes [ 496](https://github.com/rudderlabs/rudder-sdk-ios/issues/496)
=> chore(release): pulling release/2.4.4-beta into master-v2

CHANGELOG.md, README.md, Sources/Classes/Headers/RSVersion.h, Sources/Resources/PrivacyInfo.xcprivacy, package.json, sonar-project.properties
Pulling master into develop post-release v1.26.3.
=> chore(release): pulling master into develop post release v1.26.3

CHANGELOG.md, Package.swift, README.md, Sources/Classes/Headers/RSVersion.h, package.json, sonar-project.properties
Unreleased (2024-09-02)<br> * fix: fix the metrics reporter dependency version in package.swift ( 531) ([1f14447](https://github.com/rudderlabs/rudder-sdk-ios/commit/1f14447)), closes [ 531](https://github.com/rudderlabs/rudder-sdk-ios/issues/531)
=> chore(release): pulling release/1.28.1 into master

Package.swift, Podfile.lock, Rudder.podspec, Sources/Classes/RSMetricsReporter.m
- This PR includes the upgrade to the latest version (v2.0.0) of the MetricsReporter SDK, along with the necessary initialization updates for the SDK.
=> feat: update url to the metrics reporter sdk

CHANGELOG.md, Package.swift, Podfile.lock, README.md, Rudder.podspec, Sources/Classes/Headers/RSVersion.h, Sources/Classes/RSMetricsReporter.m, package.json, sonar-project.properties
Unreleased (2024-09-05)<br> * feat: update url to the metrics reporter sdk ( 535) ([b6cb20e](https://github.com/rudderlabs/rudder-sdk-ios/commit/b6cb20e)), closes [ 535](https://github.com/rudderlabs/rudder-sdk-ios/issues/535)
=> chore(release): pulling release/1.29.0 into master

.github/workflows/deploy-private-pod.yml
- This PR introduces changes to deploy the podspec.json file to a private CocoaPods repository.
=> ci: update deploy private pod step

.github/workflows/deploy-beta-cocoapods.yml
This reverts commit 551a1a2de0a3050d8f7f15a86fe0d706fb0e60ae.
=> Revert "ci: update beta github release action script (#546)"

Sources/Classes/RSUtils.m
This pull request includes updates to increase the event size limit from 32KB to 64KB.
=> feat: upgrade the maximum event size limit

.github/workflows/deploy-beta-cocoapods.yml, .github/workflows/deploy-private-pod.yml, CHANGELOG.md, Podfile.lock, README.md, Sources/Classes/Headers/RSVersion.h, Sources/Classes/RSCloudModeManager.m, Sources/Classes/RSDBPersistentManager.m, Sources/Classes/RSUtils.m, Tests/ContextTests.swift, package.json, sonar-project.properties
Unreleased (2024-11-11)<br> * feat: upgrade the maximum event size limit ( 548) ([892892d](https://github.com/rudderlabs/rudder-sdk-ios/commit/892892d)), closes [ 548](https://github.com/rudderlabs/rudder-sdk-ios/issues/548)<br> * fix: memory issue crash happening on CloudModeProcessor ( 544) ([a71ac44](https://github.com/rudderlabs/rudder-sdk-ios/commit/a71ac44)), closes [ 544](https://github.com/rudderlabs/rudder-sdk-ios/issues/544)<br> * Revert "ci: update beta github release action script ( 546)" ( 547) ([b54ed5f](https://github.com/rudderlabs/rudder-sdk-ios/commit/b54ed5f)), closes [ 546](https://github.com/rudderlabs/rudder-sdk-ios/issues/546) [ 547](https://github.com/rudderlabs/rudder-sdk-ios/issues/547)<br> * ci: update beta github release action script …
=> chore(release): pulling release/1.30.0 into master
