Example/Rudder/_AppDelegate.m, README.md, Rudder/Classes/Constants.h, Rudder/Classes/Constants.m, Rudder/Classes/EventRepository.m, Rudder/Classes/RudderConfig.h, Rudder/Classes/RudderConfig.m, Rudder/Classes/RudderConfigBuilder.h, Rudder/Classes/RudderConfigBuilder.m, Rudder/Classes/RudderServerConfigManager.m
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/16)
=> Standard naming for endPointUrl and configPlaneUrl

CHANGELOG.md, Examples/SampleSwift-iOS/SampleSwift-iOS/AppDelegate.swift, Examples/SampleSwift-iOS/SampleSwift-iOS/ViewController.swift, README.md, Rudder.podspec, Rudder.xcodeproj/project.pbxproj, Sources/Classes/Common/Constants/RSConstants.swift, Sources/Classes/Domain/Protocols/RSMessage.swift
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/176)
=> [Bugfix] Missing `properties.name` in screen calls

CHANGELOG.md, README.md, Rudder.podspec, Rudder.xcodeproj/project.pbxproj, Sources/Classes/Client/RSClient.swift, Sources/Classes/Common/Constants/RSConstants.swift, Sources/Classes/Domain/Protocols/RSMessage.swift
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/178)
=> [Bugfix] Missing `properties.name` in screen calls for device modes

Sources/Classes/Client/RSClient+Plugins.swift, Sources/Classes/Client/RSClient.swift
Relates to #182.
This makes `checkServerConfig` asynchronous and avoids blocking the main thread. Relates to https://github.com/rudderlabs/rudder-sdk-ios/issues/182.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/185)
=> Make `checkServerConfig` asynchronous

Sources/Classes/Client/Plugins/RSContextPlugin.swift, Sources/Classes/Client/RSClient.swift, Sources/Classes/Helpers/RSUserDefaults.swift
> Enhanced the `option` feature: Now if `option` is set using `setOption` API then `integration` and `customContext` value will be persisted for the successive calls. Also if any event API contains any `option` then that will completely override the `global option` (which is set using setOption API).
> Now, RESET API will reset only three things: `traits`, `externalId` (this two are same as in v1) and `userId` (newly added in v2).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-ios/193)
=> Enhanced option and reset feature

CHANGELOG.md, Examples/SampleSwift-macOS/SampleSwift-macOS.xcodeproj/project.pbxproj, README.md, Sources/Classes/Common/Constants/RSVersion.swift, Sources/Classes/Domain/Enums/JSON.swift, Sources/Classes/Helpers/Platforms/Mac/RSmacOSLifecycleEvents.swift, Sources/Classes/Helpers/Platforms/Mac/RSmacOSLifecycleMonitor.swift, package.json, sonar-project.properties
<small>2.2.4 (2022-11-16)</small><br> * fix(macOS): life cycle events were not tracking properly ([8879ff4](https://github.com/rudderlabs/rudder-sdk-ios/commit/8879ff4))<br> * ci: added CI/CD pipeline ([b7d9e78](https://github.com/rudderlabs/rudder-sdk-ios/commit/b7d9e78))<br> * ci: added CI/CD pipeline ([885b057](https://github.com/rudderlabs/rudder-sdk-ios/commit/885b057))<br> * [Bugfix] Missing  in screen calls ([b4f84e8](https://github.com/rudderlabs/rudder-sdk-ios/commit/b4f84e8))<br> * [Bugfix] Missing  in screen calls for device modes ([2663e99](https://github.com/rudderlabs/rudder-sdk-ios/commit/2663e99))<br> * [Bugfix] RSClient no longer blocks the main thread in checkServerConfig() ([83a0854](https://github.com/rudderlabs/rudder-sdk-ios/commit/83a0854))< …
=> chore(release): pulling release/2.2.5 into master

.github/workflows/create-hotfix-branch-v2.yml, .github/workflows/create-hotfix-branch.yml, CHANGELOG.md, README.md, SECURITY.md, Sources/Classes/Public/RSVersion.h, Sources/Classes/RSMessage.m, package.json, sonar-project.properties
<small>1.7.2 (2022-12-08)</small><br> * feat: remove timestamp from messageId ([a0f89fc](https://github.com/rudderlabs/rudder-sdk-ios/commit/a0f89fc))<br> * docs: added SECURITY.md ([30a657a](https://github.com/rudderlabs/rudder-sdk-ios/commit/30a657a))<br> * ci: added CI/CD pipeline for v2 ([e3d3acb](https://github.com/rudderlabs/rudder-sdk-ios/commit/e3d3acb))<br> * ci: added Slack Notification ci ([7fa84d7](https://github.com/rudderlabs/rudder-sdk-ios/commit/7fa84d7))<br> * ci: added Test & Coverage CI ([6bbe4b9](https://github.com/rudderlabs/rudder-sdk-ios/commit/6bbe4b9))<br> * ci: bump peterjgrainger/action-create-branch from 2.2.0 to 2.3.0 ([b80345a](https://github.com/rudderlabs/rudder-sdk-ios/commit/b80345a))<br> * ci: fix publish-new-release.yml …
=> chore(release): pulling release/1.8.0 into master

.github/workflows/build-and-quality-checks-v2.yml, CHANGELOG.md, Podfile.lock, README.md, Sources/Classes/Client/Plugins/RSContextPlugin.swift, Sources/Classes/Common/Constants/RSVersion.swift, package.json, sonar-project.properties
<small>2.2.5 (2023-01-20)</small><br> * fix: improper way of handling customContext ( 239) ([7a91754](https://github.com/rudderlabs/rudder-sdk-ios/commit/7a91754)), closes [ 239](https://github.com/rudderlabs/rudder-sdk-ios/issues/239)<br> * fix(macOS): life cycle events were not tracking properly ([8879ff4](https://github.com/rudderlabs/rudder-sdk-ios/commit/8879ff4))<br> * chore(release): pulling release/2.2.5 into master ([7aff1d9](https://github.com/rudderlabs/rudder-sdk-ios/commit/7aff1d9))<br> * ci: added CI/CD pipeline ([885b057](https://github.com/rudderlabs/rudder-sdk-ios/commit/885b057))<br> * [Bugfix] Missing `properties.name` in screen calls ([b4f84e8](https://github.com/rudderlabs/rudder-sdk-ios/commit/b4f84e8))<br> * [Bugfix] Missing …
=> chore(release): pulling release/2.2.6 into master

.github/workflows/deploy-cocoapods-beta.yml, CHANGELOG.md, README.md, Rudder.xcodeproj/project.pbxproj, Sources/Classes/Headers/Public/RSContext.h, Sources/Classes/Headers/Public/RSEventRepository.h, Sources/Classes/Headers/Public/RSOption.h, Sources/Classes/Headers/Public/RSPreferenceManager.h, Sources/Classes/Headers/RSVersion.h, Sources/Classes/RSContext.m, Sources/Classes/RSElementCache.m, Sources/Classes/RSEventRepository.m, Sources/Classes/RSMessage.m, Sources/Classes/RSOption.m, Sources/Classes/RSPreferenceManager.m, Tests/ContextTests.swift, Tests/TestUtils.swift, package.json, sonar-project.properties
Unreleased (2023-03-27)<br> * feat: made reset and identify api's synchronous to reflect the data immediately ( 284) ([6047fc6](https://github.com/rudderlabs/rudder-sdk-ios/commit/6047fc6)), closes [ 284](https://github.com/rudderlabs/rudder-sdk-ios/issues/284)<br> * ci: added workflows for making a beta release ( 292) ([4838b49](https://github.com/rudderlabs/rudder-sdk-ios/commit/4838b49)), closes [ 292](https://github.com/rudderlabs/rudder-sdk-ios/issues/292)
=> chore(release): pulling release/1.13.0 into master

.github/workflows/publish-new-release-v2.yml, .github/workflows/publish-new-release.yml, CHANGELOG.md, Podfile.lock, README.md, Sources/Classes/Headers/RSVersion.h, Sources/Classes/RSConfigBuilder.m, package.json, sonar-project.properties
<small>1.13.1 (2023-04-12)</small><br> * fix: restricted nil assign of dataPlaneUrl and controlPlaneUrl ( 307) ([0e28b6f](https://github.com/rudderlabs/rudder-sdk-ios/commit/0e28b6f)), closes [ 307](https://github.com/rudderlabs/rudder-sdk-ios/issues/307)<br> * chore: fix duplicate tag creation ( 306) ([6c54ed7](https://github.com/rudderlabs/rudder-sdk-ios/commit/6c54ed7)), closes [ 306](https://github.com/rudderlabs/rudder-sdk-ios/issues/306)
=> chore(release): pulling release/1.13.2 into master

Sources/Classes/Headers/Public/RSNetwork.h, Sources/Classes/RSNetwork.m
For retrieving carrier name, we are following the below steps:
* Carrier Name is deprecated in iOS versions >=16 hence we cannot get in iOS versions >= 16
* Using serviceSubscriberCellularProviders API of CTTelephonyNetworkInfo in iOS versions >= 12 and <16
* Using subscriberCellularProvider API of CTTelephonyNetworkInfo in iOS versions < 12
=> feat: added support for dual SIM carrier names

Sources/Classes/Headers/Public/RSDBPersistentManager.h, Sources/Classes/RSDBPersistentManager.m
We are appending our SQL statements which were used to insert events into the database with `returning id` to get the id in which the event got inserted to update the row in future when both cloud mode and device mode processing are done. 
However, we found that this `return` clause is not supported on iOS versions less than 15 and queries to insert events into the table are failing and hence not sent to the data plane in turn. 
Now we are following a different approach to fix this issue, we are basically retrieving the SQLite version on the device and if it's less than 3.35.0 we are using [sqlite3_last_insert_rowid](https://www.sqlite.org/c3ref/last_insert_rowid.html) to get the row id of last inserted row and `return` clause as usual if the SQLite version on the device is greater than …
=> fix: fixed insert sql statements to support sqlite versions less than 3.35.0

Podfile.lock, Rudder.xcodeproj/project.pbxproj, Sources/Classes/Headers/Public/NSData+GZIP.h, Sources/Classes/Headers/Public/RSConfig.h, Sources/Classes/Headers/Public/RSConfigBuilder.h, Sources/Classes/Headers/Public/RSConstants.h, Sources/Classes/NSData+GZIP.m, Sources/Classes/RSConfig.m, Sources/Classes/RSConfigBuilder.m, Sources/Classes/RSConstants.m, Sources/Classes/RSNetworkManager.m
=> feat: added support for gzip

.github/workflows/draft-new-release-v2.yml, .github/workflows/draft-new-release.yml
Lock conventional-changelog-cli to 2.2.2 in draft-new-release CIs
=> chore: lock conventional-changelog-cli to 2.2.2 in draft-new-release CIs

Podfile.lock, Sources/Classes/Headers/Public/RSApplicationLifeCycleManager.h, Sources/Classes/Headers/Public/RSDBPersistentManager.h, Sources/Classes/Headers/Public/RSDeviceModeManager.h, Sources/Classes/Headers/Public/RSEventRepository.h, Sources/Classes/Headers/Public/RSPreferenceManager.h, Sources/Classes/Headers/Public/RSUtils.h, Sources/Classes/RSApplicationLifeCycleManager.m, Sources/Classes/RSDBPersistentManager.m, Sources/Classes/RSDeviceModeManager.m, Sources/Classes/RSEventRepository.m, Sources/Classes/RSPreferenceManager.m, Sources/Classes/RSUtils.m
- While SDK updated for the first time from the version containing the issue to the latest version containing the fix:
- Mark all the previous events whose statuses are 0 and 2 to device_mode_processing_done and remove events whose status code is updated to 3.
- Any event made after the SDK update will be sent to makeFactoryDump.
- Also, if the user updates again to any newer version containing this fix, then the SDK will send an event with status codes 0 and 2 to makeFactoryDump instead of directly marking it as device_mode_processing_done.
- Handle network issues where events are not sent to the device mode integrations and remained stored in the DB. Now, if such a case happens then the event will be sent to device mode factories and when cloud mode processing is done, it’ll be removed …
=> fix: event not getting removed from DB and certain processing issue

Sources/Classes/RSApplicationLifeCycleManager.m, Sources/Classes/RSEventRepository.m
When tracking the life cycle events is disabled, we are not saving the build number and version number to preferences as a result when this flag is enabled in future then Application Installed/Updated is getting triggered, which is kind of in-correct, hence we fixed this by saving build number and version number irrespective of whether life cycle events are enabled or not.
=> fix: fixed application installed, updated triggered in-correctly

Sources/Classes/RSEventRepository.m
The previous automatic session would still be active, if we disable the track life cycle events on next launch, hence we need to save the automatic tracking status as enabled in the preferences only when both track life cycle events and automatic session tracking is enabled.
=> fix: auto-session  un-cleared on dynamically disabling trackLifeCycleEvents & autoSessionTracking

CHANGELOG.md, Podfile.lock, README.md, Sources/Classes/Headers/Public/NSData+GZIP.h, Sources/Classes/Headers/Public/RSApplicationLifeCycleManager.h, Sources/Classes/Headers/Public/RSDBMessage.h, Sources/Classes/Headers/Public/RSDBPersistentManager.h, Sources/Classes/Headers/Public/RSDeviceModeManager.h, Sources/Classes/Headers/Public/RSEnums.h, Sources/Classes/Headers/Public/RSPreferenceManager.h, Sources/Classes/Headers/Public/RSUtils.h, Sources/Classes/Headers/RSVersion.h, Sources/Classes/NSData+GZIP.m, Sources/Classes/RSApplicationLifeCycleManager.m, Sources/Classes/RSDBPersistentManager.m, Sources/Classes/RSDeviceModeManager.m, Sources/Classes/RSEventRepository.m, Sources/Classes/RSPreferenceManager.m, Sources/Classes/RSUtils.m, Tests/DBPersistentManagerTests.swift, package.json, sonar-project.properties
Unreleased (2023-07-31)<br> * fix: event not getting removed from DB and certain processing issue ( 340) ([54d210c](https://github.com/rudderlabs/rudder-sdk-ios/commit/54d210c)), closes [ 340](https://github.com/rudderlabs/rudder-sdk-ios/issues/340)<br> * fix: fixed application installed and updated getting triggered in-correctly ( 345) ([cbdf123](https://github.com/rudderlabs/rudder-sdk-ios/commit/cbdf123)), closes [ 345](https://github.com/rudderlabs/rudder-sdk-ios/issues/345)<br> * fix: fixed automatic session not getting cleared on dynamically disabling track life cycle events (  ([0b580d9](https://github.com/rudderlabs/rudder-sdk-ios/commit/0b580d9)), closes [ 344](https://github.com/rudderlabs/rudder-sdk-ios/issues/344)<br> * fix: replay message queue …
=> chore(release): pulling release/1.16.1 into master

Sources/Classes/Client/RSClient+Plugins.swift, Sources/Classes/Client/RSController.swift
On the first app launch, events were not recorded for the device modes on the first launch. It works ok on the second launch.
=> fix: no events recorded for dm destinations on the first launch

Sources/Classes/Headers/Public/Rudder.h
Header not found issue on Flutter.
=> fix: header not found issue on cross platforms

Sources/Classes/RSDBPersistentManager.m
After the database is encrypted, iOS drops the encrypted DB and should create a new one when a wrong password is provided.
=> fix: db encryption improvements

Sources/Classes/Headers/Public/RSClient.h, Sources/Classes/Headers/Public/RSEventRepository.h, Sources/Classes/RSClient.m, Sources/Classes/RSEventRepository.m, Tests/RudderUtilsTest.swift, Tests/UserSessionTests.swift
=> feat: get session_id

.github/workflows/deploy-cocoapods.yml, .github/workflows/deploy-private-pod.yml, .github/workflows/slack-notify.yml, CHANGELOG.md, README.md, Sources/Classes/Headers/RSVersion.h, Sources/Classes/RSDBPersistentManager.m, package.json, sonar-project.properties
1.21.0 (2023-09-28)<br> * fix: crash on RSDBPersistentManager ([b645316](https://github.com/rudderlabs/rudder-sdk-ios/commit/b645316))<br> * chore(ci): private pod release workflow added and other improvements ( 394) ([2960118](https://github.com/rudderlabs/rudder-sdk-ios/commit/2960118)), closes [ 394](https://github.com/rudderlabs/rudder-sdk-ios/issues/394)<br> * chore(release): 1.21.0 ([f8ce0f7](https://github.com/rudderlabs/rudder-sdk-ios/commit/f8ce0f7))<br> * feat: improvements of SQLite RETURNING clause ([00e5032](https://github.com/rudderlabs/rudder-sdk-ios/commit/00e5032))
=> chore(release): pulling hotfix-release/1.22.0 into master

.github/workflows/deploy-cocoapods.yml, .github/workflows/deploy-private-pod.yml, .github/workflows/draft-new-beta-release.yml, .github/workflows/slack-notify.yml, Rudder.podspec
=> chore(ci): fix workflows

Examples/RudderSampleAppObjC/RudderSampleAppObjC/_AppDelegate.m, Podfile.lock, Sources/Classes/Headers/Public/RSClient.h, Sources/Classes/Headers/Public/RSDeviceModeManager.h, Sources/Classes/Headers/Public/RSEventRepository.h, Sources/Classes/Headers/Public/RSIntegration.h, Sources/Classes/RSClient.m, Sources/Classes/RSDeviceModeManager.m, Sources/Classes/RSEventRepository.m
- Added `onIntegrationReady` API to get the native instance of the integration SDKs.
- This API needs to be gradually implemented in all the integration SDKs.
=> feat: provide onIntegrationReady API support

CHANGELOG.md, Examples/RudderSampleAppObjC/RudderSampleAppObjC.xcodeproj/project.pbxproj, Examples/RudderSampleAppObjC/RudderSampleAppObjC.xcodeproj/xcshareddata/xcschemes/RudderSampleAppObjC.xcscheme, Examples/RudderSampleAppSwift/RudderSampleAppSwift.xcodeproj/project.pbxproj, Examples/RudderSampleApptvOSObjC/RudderSampleApptvOSObjC.xcodeproj/project.pbxproj, Examples/RudderSampleAppwatchOSObjC/RudderSampleAppwatchOSObjC.xcodeproj/project.pbxproj, Podfile.lock, README.md, Rudder.podspec, Rudder.xcodeproj/project.pbxproj, Sources/Classes/Headers/RSVersion.h, package.json, sonar-project.properties
Unreleased (2023-12-20)<br> * chore: bumped version of MetricsReporter to 1.2.0 ( 427) ([da6150d](https://github.com/rudderlabs/rudder-sdk-ios/commit/da6150d)), closes [ 427](https://github.com/rudderlabs/rudder-sdk-ios/issues/427)
=> chore(release): pulling release/1.24.1 into master

.github/workflows/publish-new-release.yml, Scripts/generate-xcframework.sh
> This action will generate XCFrameworks file for iOS-v1 SDK. 
Reference: https://github.com/rudderlabs/rudder-sdk-ios/issues/410.
**NOTE**: iOS-v2 SDK is still in beta. Once we release a stable version, we will implement a similar action.
=> chore(ci): add steps to generate xcframework files while releasing the sdk

.github/workflows/publish-new-release.yml, CHANGELOG.md, Package.swift, Podfile.lock, README.md, Rudder.podspec, Rudder.xcodeproj/project.pbxproj, Scripts/generate-xcframework.sh, Sources/Classes/Headers/RSVersion.h, package.json, sonar-project.properties
Unreleased (2024-01-03)<br> * fix: updated version of MetricsReporter in package.swift ( 433) ([8870ccd](https://github.com/rudderlabs/rudder-sdk-ios/commit/8870ccd)), closes [ 433](https://github.com/rudderlabs/rudder-sdk-ios/issues/433)<br> * chore(ci): add steps to generate xcframework files while releasing the sdk ( 428) ([690d8ff](https://github.com/rudderlabs/rudder-sdk-ios/commit/690d8ff)), closes [ 428](https://github.com/rudderlabs/rudder-sdk-ios/issues/428)
=> chore(release): pulling release/1.24.2 into master

.github/workflows/publish-new-release.yml
- I've updated the platform to `macOS` to fix the `Publish New Release` GitHub action which failed while installing XCPretty.
=> chore(ci): change the platform from ubuntu to macOS

CHANGELOG.md, README.md, Sources/Classes/Common/Constants/RSVersion.swift, Sources/Classes/Utility/RSUtils.swift, package.json, sonar-project.properties
Unreleased (2024-01-18)<br> * fix: fixed sqlite db path on the tvos platforms ( 417) ([e8bfe4a](https://github.com/rudderlabs/rudder-sdk-ios/commit/e8bfe4a)), closes [ 417](https://github.com/rudderlabs/rudder-sdk-ios/issues/417)
=> chore(release): pulling release/2.4.3 into master

.github/workflows/draft-new-beta-release.yml
* Updated the Runnder to macOS-latest so that Cocoapods would be installed.
* Updated the workflow to be executed on `feature/` branches as well.
=> ci: fixed failing draft new beta release workflow

Sources/Classes/RSContext.m, Sources/Classes/RSDeviceModeTransformationManager.m
* Fixed in-correct nil checks for de-serializing Traits and ExternalIds from preferences
=> fix: nil check errors after de-serialization

.github/workflows/publish-new-release.yml
- We faced an issue where some portion of the same github action codes required the `macOS` platform and others required `Ubuntu` to complete their actions. So to fix that: I've separated the required code into separate jobs, assigning the respective platform required to complete the task.
- Here is a **demo** run of this action:
**Note**: We cannot create a separate GitHub Action altogether, as upload of XCFramework requires that the `Releases` tag be first generated, which happens in the first portion (or job) of the code.
=> chore(ci): fix publish new release github action

Podfile.lock, Rudder.podspec
- Correct the file name of the `LICENSE.md` file in the `Rudder.Podspec` file.
=> fix: correct file name of LICENSE.md file in Podspec

.github/workflows/slack-notify.yml, CHANGELOG.md, Podfile.lock, README.md, Rudder.xcodeproj/project.pbxproj, Rudder.xcodeproj/xcshareddata/xcschemes/RudderTests-iOS.xcscheme, Rudder.xcodeproj/xcshareddata/xcschemes/RudderTests-tvOS.xcscheme, Rudder.xcodeproj/xcshareddata/xcschemes/RudderTests-watchOS.xcscheme, Sources/Classes/Headers/Public/RSDefaultsPersistence.h, Sources/Classes/Headers/Public/RSEventRepository.h, Sources/Classes/Headers/Public/RSPreferenceManager.h, Sources/Classes/Headers/Public/RSUtils.h, Sources/Classes/Headers/RSVersion.h, Sources/Classes/RSDefaultsPersistence.m, Sources/Classes/RSEventRepository.m, Sources/Classes/RSPreferenceManager.m, Sources/Classes/RSUtils.m, Tests/DefaultsPersistenceTests.swift, package.json, sonar-project.properties
Unreleased (2024-02-20)<br> * fix: added a persistence layer over keys stored in standard defaults by rudderstack ( 454) ([1c52a07](https://github.com/rudderlabs/rudder-sdk-ios/commit/1c52a07)), closes [ 454](https://github.com/rudderlabs/rudder-sdk-ios/issues/454)<br> * chore(deps): bump slackapi/slack-github-action from 1.24.0 to 1.25.0 ( 451) ([f633573](https://github.com/rudderlabs/rudder-sdk-ios/commit/f633573)), closes [ 451](https://github.com/rudderlabs/rudder-sdk-ios/issues/451)
=> chore(release): pulling release/1.25.2 into master

Examples/RudderSampleAppObjC/RudderSampleAppObjC.xcodeproj/project.pbxproj, Examples/RudderSampleAppObjC/RudderSampleAppObjC/Base.lproj/Main.storyboard, Examples/RudderSampleAppObjC/RudderSampleAppObjC/_AppDelegate.h, Examples/RudderSampleAppObjC/RudderSampleAppObjC/_AppDelegate.m, Examples/RudderSampleAppObjC/RudderSampleAppObjC/_ViewController.m, Podfile.lock, Rudder.xcodeproj/project.pbxproj, Sources/Classes/Headers/Public/RSClient.h, Sources/Classes/Headers/Public/RSContext.h, Sources/Classes/Headers/Public/RSDeviceInfo.h, Sources/Classes/Headers/Public/RSPreferenceManager.h, Sources/Classes/Headers/Public/RSUtils.h, Sources/Classes/RSClient.m, Sources/Classes/RSContext.m, Sources/Classes/RSDeviceInfo.m, Sources/Classes/RSPreferenceManager.m, Sources/Classes/RSUtils.m
* Added Support for setting `advertisingId` before SDK initialization by adding a new static method `putAdvertisementId` in RSClient. Now all the life cycle events which were triggered as part of SDK initialization like `Application Installed`, `Application Opened` would also contain the `advertisingId` in them.
* Added Support for persisting advertisingId so that all the events made in the subsequent launches would also contain the advertisingId in them.
* Added a new method `clearAdvertisingId` in RSClient to enable the clearing of `advertisingId` when needed.
=> feat: added support for setting advertisingId before sdk init and also persisting it

CHANGELOG.md, Examples/RudderSampleAppObjC/RudderSampleAppObjC.xcodeproj/project.pbxproj, Examples/RudderSampleAppObjC/RudderSampleAppObjC/Base.lproj/Main.storyboard, Examples/RudderSampleAppObjC/RudderSampleAppObjC/_AppDelegate.h, Examples/RudderSampleAppObjC/RudderSampleAppObjC/_AppDelegate.m, Examples/RudderSampleAppObjC/RudderSampleAppObjC/_ViewController.m, Podfile.lock, README.md, Rudder.xcodeproj/project.pbxproj, Sources/Classes/Headers/Public/RSClient.h, Sources/Classes/Headers/Public/RSContext.h, Sources/Classes/Headers/Public/RSDeviceInfo.h, Sources/Classes/Headers/Public/RSPreferenceManager.h, Sources/Classes/Headers/Public/RSUtils.h, Sources/Classes/Headers/RSVersion.h, Sources/Classes/RSClient.m, Sources/Classes/RSContext.m, Sources/Classes/RSDeviceInfo.m, Sources/Classes/RSEventRepository.m, Sources/Classes/RSPreferenceManager.m, Sources/Classes/RSUtils.m, package.json, sonar-project.properties
Unreleased (2024-03-19)<br> * feat: add support for global customContext option ( 485) ([27f21b9](https://github.com/rudderlabs/rudder-sdk-ios/commit/27f21b9)), closes [ 485](https://github.com/rudderlabs/rudder-sdk-ios/issues/485)<br> * feat: added support for setting advertisingId before sdk init and also persisting it ( 481) ([2075910](https://github.com/rudderlabs/rudder-sdk-ios/commit/2075910)), closes [ 481](https://github.com/rudderlabs/rudder-sdk-ios/issues/481)
=> chore(release): pulling release/1.26.0 into master

Sources/Classes/RSMetricsReporter.m
* initializing MetricsReporter and CrashReporter only if it's enabled for a customer
=> fix: rectified incorrect initialization of MetricsReporter and CrashReporter

CHANGELOG.md, CODEOWNERS, README.md, Sources/Classes/Headers/RSVersion.h, Sources/Classes/RSMetricsReporter.m, package.json, sonar-project.properties
Unreleased (2024-03-28)<br> * chore: updated CODEOWNERS to point to iOS team ([45646af](https://github.com/rudderlabs/rudder-sdk-ios/commit/45646af))<br> * fix: initializing MetricsReporter and CrashReporter only if it's enabled for a customer ( 491) ([48c4ae1](https://github.com/rudderlabs/rudder-sdk-ios/commit/48c4ae1)), closes [ 491](https://github.com/rudderlabs/rudder-sdk-ios/issues/491)
=> chore(release): pulling release/1.26.1 into master

RudderTests/Core/SourceConfigDownload/SourceConfigDownloadTests.swift, RudderTests/Core/SourceConfigDownload/SourceConfigDownloadWorkerTests.swift, RudderTests/Core/Storage/StorageMigratorTests.swift, RudderTests/Mocks/CoreMocks.swift, Sources/Classes/Core/Common/Constants/LogMessages.swift, Sources/Classes/Core/Helpers/UserDefaultsWorker.swift, Sources/Classes/Core/RSClient.swift, Sources/Classes/Core/RSClientCore.swift, Sources/Classes/Core/SourceConfigDownload/SourceConfigDownload.swift, Sources/Classes/Core/SourceConfigDownload/SourceConfigDownloadWorker.swift, Sources/Classes/Core/Storage/Migration/StorageMigration.swift, Sources/Classes/Core/Storage/Migration/StorageMigrator.swift
* Fixed the issue of reading Legacy Source Config from Suited Name instance of User Defaults and started reading it from Standard Defaults
* Fixed the issue of Legacy SQLiteStorage not opened while performing migration. 
* Removed the responsibility of determining if database migration is required from the SourceConfig Downloader Module and handed it over to each migrator to determine if migration is needed.
* Removed the support for Customising the Storage Migrator by the user.
* Added tests for successful and failed migration scenarios.
=> fix: fixed issues with the database migration when moving from v1 to v2.

Sources/Classes/Helpers/Platforms/iOS/RSiOSScreenViewEvents.swift
This PR fixes the name mangling of the screen events when the automatic screen tracking tries to capture SwiftUI's views.
The issue was cause by the usage of `NSStringFromClass`, that takes the unique mangled name of a Swift class as seen from the ObjC runtime. Using Swift's standard library `String(describing: type(of: self))` instead returns us the demangled name.
I have implemented this feature on top of the 2.4.3 tag. I'm unsure of what branch to target.
Here's an example: 
| Before | After |
| --- | --- |
| <img width="1036" alt="Screenshot 2024-02-28 at 15 23 00" src="https://github.com/rudderlabs/rudder-sdk-ios/assets/15340382/aca97d20-a464-4e9e-aa1e-6707fd8898af"> | <img width="564" alt="Screenshot 2024-02-28 at 15 22 48" …
=> fix: fix SwiftUI mangled names

CHANGELOG.md, CODEOWNERS, README.md, Sources/Classes/Common/Constants/RSVersion.swift, Sources/Classes/Helpers/Platforms/iOS/RSiOSScreenViewEvents.swift, package.json, sonar-project.properties
Unreleased (2024-04-05)<br> * fix: fix swift name mangling for SwiftUI hosting controllers ( 475) ([dbb04b5](https://github.com/rudderlabs/rudder-sdk-ios/commit/dbb04b5)), closes [ 475](https://github.com/rudderlabs/rudder-sdk-ios/issues/475)<br> * chore: updated CODEOWNERS to point to a team ([d2bad2d](https://github.com/rudderlabs/rudder-sdk-ios/commit/d2bad2d))
=> chore(release): pulling release/2.4.4-beta into master-v2

Package.swift, Podfile.lock, Rudder.podspec, Sources/Classes/Common/Constants/RSConstants.swift, Sources/Resources/PrivacyInfo.xcprivacy
- Added Privacy Manifest file support for iOS v2 SDK: Implemented support for Privacy Manifest file in both CocoaPods and Swift Package Manager (SPM) distributions.
- Changed `rudderlabs` domain to `rudderstack.com` for default dataPlane and controlPlaneUrl.
- Changed mail to `sdk@rudderstack.com`.
Here is the Privacy Report:
=> feat: add privacy manifest file support for ios v2 sdk

.github/workflows/check-pr-title.yml, .github/workflows/create-hotfix-branch-v2.yml, .github/workflows/create-hotfix-branch.yml, .github/workflows/draft-new-release.yml, .github/workflows/publish-new-release.yml, CHANGELOG.md, Package.swift, README.md, Rudder.podspec, Sources/Classes/Headers/RSVersion.h, Sources/Resources/PrivacyInfo.xcprivacy, package.json, sonar-project.properties
Unreleased (2024-04-08)<br> * ci: change the PR reviewer to sdk team ( 500) ([c5507f5](https://github.com/rudderlabs/rudder-sdk-ios/commit/c5507f5)), closes [ 500](https://github.com/rudderlabs/rudder-sdk-ios/issues/500)<br> * fix: resolve issue with privacy manifest file not being generated when consumed through SPM ( 499) ([1d6761f](https://github.com/rudderlabs/rudder-sdk-ios/commit/1d6761f)), closes [ 499](https://github.com/rudderlabs/rudder-sdk-ios/issues/499)<br> * chore(deps): bump peterjgrainger/action-create-branch ( 476) ([6867d8e](https://github.com/rudderlabs/rudder-sdk-ios/commit/6867d8e)), closes [ 476](https://github.com/rudderlabs/rudder-sdk-ios/issues/476)<br> * chore(deps): bump rudderlabs/github-action-check-pr-title ( 486) …
=> chore(release): pulling release/1.26.2 into master

Sources/Resources/PrivacyInfo.xcprivacy
- We've decided to remove the tracking domain URL from the Privacy Manifest file. This change aims to resolve the error that occurs when a request to our tracking domain gets blocked after the user denies tracking permission.
=> fix: remove tracking domain url from Privacy Manifest file

CHANGELOG.md, README.md, Sources/Classes/Headers/RSVersion.h, Sources/Resources/PrivacyInfo.xcprivacy, package.json, sonar-project.properties
Unreleased (2024-04-22)<br> * fix: remove tracking domain url from Privacy Manifest file ( 509) ([759a9f3](https://github.com/rudderlabs/rudder-sdk-ios/commit/759a9f3)), closes [ 509](https://github.com/rudderlabs/rudder-sdk-ios/issues/509)
=> chore(release): pulling release/1.26.3 into master

CHANGELOG.md, Podfile.lock, README.md, Sources/Classes/Common/Constants/RSVersion.swift, Sources/Resources/PrivacyInfo.xcprivacy, package.json, sonar-project.properties
Unreleased (2024-04-24)<br> * fix: remove tracking domain url from Privacy Manifest file in v2 ( 514) ([533e8e1](https://github.com/rudderlabs/rudder-sdk-ios/commit/533e8e1)), closes [ 514](https://github.com/rudderlabs/rudder-sdk-ios/issues/514)
=> chore(release): pulling release/2.5.1-beta into master-v2

CONTRIBUTING.md
We are going to use the new CLA (Google Form link) instead of the old Wufoo link to improve organisation and reduce management/collaboration hassles
=> docs: update cla link

.github/workflows/test.yml
- Change from `macos-latest` to `macos-latest-large` only for `Tests & Coverage` GitHub Action. This is to fix the sonar cloud installation issue occurring in https://github.com/rudderlabs/rudder-sdk-ios/pull/520 and https://github.com/rudderlabs/rudder-sdk-ios/pull/518.
=> ci: change the latest platform to macos-latest-large

Podfile.lock, Rudder.xcodeproj/project.pbxproj, Sources/Classes/Headers/Public/RSConstants.h, Sources/Classes/Headers/Public/RSExponentialBackOff.h, Sources/Classes/Headers/Public/RSUtils.h, Sources/Classes/RSCloudModeManager.m, Sources/Classes/RSConstants.m, Sources/Classes/RSExponentialBackOff.m, Sources/Classes/RSUtils.m
- This PR removes the existing retry mechanism for network errors and replaces it with an **exponential retry mechanism with jitter**. Now, retries will occur exponentially for every **4xx** and **5xx** status code (except 400 and 404). If the network is unavailable, retries will continue with a one-second delay.
- The maximum limit is 5 minutes; once this limit is reached, the retry process will start over from the beginning.
- Example sequence:
```
6s, 8s, 15s, 28s, 1m 35s, 2m 48s, 3m 49s, 5m 0s,
4s, 6s, 24s, 31s..
```
**NOTE**: No event is deleted in this process.
=> feat: implement exponential retry mechanism for handling network errors

Sources/Classes/RSContext.m
- This PR has the fix for missing `anonymousId` under `context.traits` section on second identify event with different `userId`.
=> fix: set anonymousId in traits when second Identify event is made

.github/ISSUE_TEMPLATE/bug_report.md, .github/workflows/draft-new-release-v2.yml, CHANGELOG.md, Podfile.lock, README.md, Rudder.xcodeproj/project.pbxproj, Sources/Classes/Headers/Public/RSConstants.h, Sources/Classes/Headers/Public/RSExponentialBackOff.h, Sources/Classes/Headers/Public/RSUtils.h, Sources/Classes/Headers/RSVersion.h, Sources/Classes/RSCloudModeManager.m, Sources/Classes/RSConstants.m, Sources/Classes/RSContext.m, Sources/Classes/RSExponentialBackOff.m, Sources/Classes/RSUtils.m, package.json, sonar-project.properties
Unreleased (2024-08-07)<br> * fix: set anonymousId in traits when second Identify event is made ( 526) ([b52251b](https://github.com/rudderlabs/rudder-sdk-ios/commit/b52251b)), closes [ 526](https://github.com/rudderlabs/rudder-sdk-ios/issues/526)<br> * feat: implement exponential retry mechanism for handling network errors ( 525) ([8bf2900](https://github.com/rudderlabs/rudder-sdk-ios/commit/8bf2900)), closes [ 525](https://github.com/rudderlabs/rudder-sdk-ios/issues/525)<br> * chore: remove Bug Fixes section from the CHANGELOG file ([14f8425](https://github.com/rudderlabs/rudder-sdk-ios/commit/14f8425))<br> * chore: update pr_reviewer and assignees to @rudderlabs/sdk-ios ( 518) ([c3ed790](https://github.com/rudderlabs/rudder-sdk-ios/commit/c3ed790)), closes [ …
=> chore(release): pulling release/1.28.0 into master

Sources/Classes/RSCloudModeManager.m, Sources/Classes/RSDBPersistentManager.m
- This PR resolves a significant memory issue that was causing crashes in the CloudModeProcessor class.
- To fix this, we’ve updated the method for reading events in cloud mode to enhance memory management.
- Additionally, the implementation now includes catching potential errors and providing users with a debug log for better insight into the issue.
=> fix: memory issue crash happening on CloudModeProcessor

.github/workflows/deploy-private-pod.yml, CHANGELOG.md, README.md, Sources/Classes/Headers/RSVersion.h, Sources/Classes/RSCloudModeManager.m, Sources/Classes/RSDBPersistentManager.m, package.json, sonar-project.properties
Unreleased (2024-10-07)<br> * ci: update deploy private pod step ( 541) ([6c4f845](https://github.com/rudderlabs/rudder-sdk-ios/commit/6c4f845)), closes [ 541](https://github.com/rudderlabs/rudder-sdk-ios/issues/541)<br> * fix: memory issue crash happening on CloudModeProcessor ([ddc2d05](https://github.com/rudderlabs/rudder-sdk-ios/commit/ddc2d05))
=> chore(release): pulling release/1.29.1 into master

.github/workflows/deploy-beta-cocoapods.yml
In this PR, we removed the beta release prefix check in order to release the beta SDK.
We will revert this change after the beta release.
=> ci: update beta github release action script

Podfile.lock, Sources/Classes/RSClient.m
- In the existing `alias` API, set `anonymousId` as `previousId`, if `userId` is not present. 
- This case will happen when an `alias` event is made before any `identify` event is made. In this case, `previousId` needs to be set as `anonymousId` but currently this field is not present. So we've added a fix to add the correct value.
=> fix: set anonymousId as previousId in alias API if userId is not present

Podfile.lock, Sources/Classes/Headers/Public/RSClient.h, Sources/Classes/RSClient.m
- Added an `Alias` API with `previousId` support. Now, `previousId` can be passed and will be preferred over the existing `userId` or `anonymousId`.
- New Alias API:
```
- (void) alias:(NSString *)newId previousId:(NSString * _Nullable)previousId options:(RSOption * _Nullable) options;
```
- This is to bring it in parity with the JS SDK so that `previousId` can be explicitly passed if needed.
NOTE: The change is backwards compatible, as we are introducing a new Alias API which adds a new behaviour to the existing payload schema.
Objective: We need to test, if `previousId` is passed then it should be used, else the existing behaviour should continue i.e., userId or anonymousId should be used.
- Make an `alias` event and explicitly pass `previousId` field -> It should be set as the …
=> feat: add alias api with previousId support
